# Test your FastAPI endpoints

GET http://127.0.0.1:8000/books/
Accept: application/json

###

POST http://127.0.0.1:8000/products/
Content-Type: application/json

{
  "name": "Kamado Tanjiro",
  "stock": 12,
  "price": 199.99
}

###

PUT http://127.0.0.1:8000/products/6a2541995be251f781087f4a
Content-Type: application/json

{
  "name": "Kamado Nezuko"
}

###

DELETE http://127.0.0.1:8000/products/6a24db90ed4ac164a0b9c68f
Accept: application/json

###