# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/2
Accept: application/json

###

POST 127.0.0.1:8000/
Content-Type: application/json

{
  "id": 3,
  "first_name": "Kamado",
  "last_name": "Nezuko",
  "age": 15
}

###